---

.comm.base:
  variables:
    PKG_DIR: "comm"

comm.flake8:
  extends:
    - .comm.base
    - .base
  script:
    - eval "$(envo --dry-run)"
    - flake8

comm.mypy:
  extends:
    - .comm.base
    - .base
  script:
    - eval "$(envo --dry-run)"
    - mypy .


comm.test 1/3:
  image: python:3.8.2-slim-buster
  extends:
    - .comm.base
    - .base
  script:
    - eval "$(envo --dry-run)"
    - pytest tests

comm.test 2/3:
  image: python:3.7-slim-buster
  extends:
    - .comm.base
    - .base
  script:
    - eval "$(envo --dry-run)"
    - pytest tests

comm.test 3/3:
  image: python:3.6-slim-buster
  extends:
    - .comm.base
    - .base
  script:
    - eval "$(envo --dry-run)"
    - pytest tests
