repos:
-   repo: local
    hooks:
      - id: isort
        name: Make it isorty.
        entry: .bin/isort
        language: script
        files: '.*.py'

      - id: black
        name: Make it black.
        entry: .bin/black
        language: script
        files: '.*.py'
