---

secrets:
  htpasswd: "user:$2y$05$h2KCwGYRI3wVfmnNPecmgeA259G7WIYWMDE0fDXADXJvuQVIKJ2OW"

ingress:
  enabled: true
  hosts:
    - {{ ingress.host }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ingress.class: "nginx"

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  size: 50Gi
