---
stages:
  - test
  - publish

.base:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}:${CI_JOB_NAME}
    paths:
      - .venv
  image: python:3.8.2-slim-buster
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install poetry==1.0.5
    - poetry config virtualenvs.create true
    - poetry config virtualenvs.in-project true
    - poetry install

include:
  - "/comm/.gitlab-ci.yaml"
  - "/envo/.gitlab-ci.yaml"
  - "/pangea/.gitlab-ci.yaml"
  - "/rhei/.gitlab-ci.yaml"
  - "/stickybeak/.gitlab-ci.yaml"


