---
stages:
  - test
  - publish

.base:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}:${CI_JOB_NAME}
    paths:
      - .venv
  image: python:3.8.2-slim-buster

  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install poetry==1.0.5
    # install common monorepo packages
    - poetry config virtualenvs.create true
    - poetry config virtualenvs.in-project true
    - poetry install
    - cd $PKG_DIR
    - poetry config virtualenvs.create true
    - poetry config virtualenvs.in-project true
    - poetry install
    - eval "$(envo --dry-run)"

include:
  - "/comm/.gitlab-ci.yml"
  - "/envo/.gitlab-ci.yml"
#  - "/pangea/.gitlab-ci.yml"
#  - "/rhei/.gitlab-ci.yml"
#  - "/stickybeak/.gitlab-ci.yml"
