---

flake8:
  extends:
    - .base
  script:
    - poetry run flake8

mypy:
  extends:
    - .base
  script:
    - poetry run mypy .

test 1/3:
  image: python:3.8.2-slim-buster
  extends:
    - .base
  script:
    - poetry run pytest tests

test 2/3:
  image: python:3.7-slim-buster
  extends:
    - .base
  script:
    - poetry run pytest tests

test 3/3:
  image: python:3.6-slim-buster
  extends:
    - .base
  script:
    - poetry run pytest tests


publish:
  stage: publish

  extends:
    - .base
  script:
    - ./.bin/recreate_stubs
    - poetry build
    - poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD

  only:
    changes:
      - envo/pyproject.toml
    refs:
      - master
