---

.envo.base:
  variables:
    PKG_DIR: "envo"

envo.flake8:
  extends:
    - .envo.base
    - .base
  script:
    - poetry run flake8

envo.mypy:
  extends:
    - .envo.base
    - .base
  script:
    - poetry run mypy .

envo.test 1/3:
  image: python:3.8.2-slim-buster
  extends:
    - .envo.base
    - .base
  script:
    - poetry run pytest tests

envo.test 2/3:
  image: python:3.7-slim-buster
  extends:
    - .envo.base
    - .base
  script:
    - poetry run pytest tests

envo.test 3/3:
  image: python:3.6-slim-buster
  extends:
    - .envo.base
    - .base
  script:
    - poetry run pytest tests


envo.publish:
  stage: publish

  extends:
    - .envo.base
    - .base
  script:
    - ./.bin/recreate_stubs
    - poetry build
    - poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD

  only:
    changes:
      - envo/pyproject.toml
    refs:
      - master
