repos:
-   repo: local
    hooks:
      - id: isort
        name: Sort imports.
        entry: .bin/isort
        language: script
        files: '.*.py'
        exclude: "envo/templates"

      - id: black
        name: Make it black.
        entry: .bin/black
        language: script
        files: '.*.py'
        exclude: "envo/templates"
