---

.pangea.base:
  variables:
    PKG_DIR: "pangea"

pangea.flake8:
  extends:
    - .pangea.base
    - .base
  script:
    - eval "$(pangea --dry-run)"
    - flake8

pangea.mypy:
  extends:
    - .pangea.base
    - .base
  script:
    - eval "$(pangea --dry-run)"
    - mypy .

pangea.test 1/3:
  image: python:3.8.2-slim-buster
  extends:
    - .pangea.base
    - .base
  script:
    - eval "$(pangea --dry-run)"
    - pytest tests

pangea.test 2/3:
  image: python:3.7-slim-buster
  extends:
    - .pangea.base
    - .base
  script:
    - pytest tests

pangea.test 3/3:
  image: python:3.6-slim-buster
  extends:
    - .pangea.base
    - .base
  script:
    - eval "$(pangea --dry-run)"
    - pytest tests


pangea.publish:
  stage: publish

  extends:
    - .pangea.base
    - .base
  script:
    - poetry run ./.bin/recreate_stubs
    - poetry run ./.bin/generate_version
    - poetry build
    - poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD

  only:
    changes:
      - pangea/pyproject.toml
    refs:
      - master
